### ISSUE TITLE
Are these boundaries current?

### ISSUE THREAD

**Issue by adelevie** [JeffreyBLewis/congressional-district-boundaries#1]
May sound like a dumb question, but given that we're currently in the 113th Congress, are these files not suitable for describing current districts?

**Comment by JeffreyBLewis** [comment]
Dear Alan,

That is is good question.  I have not yet incorporated the new 113th 
districts into my collection, you can download them at 
http://www.census.gov/cgi-bin/geo/shapefilesrd13/layers.cgi.   I hope to 
do that in the next month or two.

Best,

Jeff

On 07/22/2013 10:56 AM, Alan deLevie wrote:

> May sound like a dumb question, but given that we're currently in the 
> 113th Congress, are these files not suitable for describing current 
> districts?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/JeffreyBLewis/congressional-district-boundaries/issues/1.

## 

Jeffrey Lewis
Professor and Chair
Department of Political Science
UCLA

**Comment by adelevie** [comment]
For some reason nothing is showing up when I click the link. There's just a
page title, but no content related to downloading the 2013 files.

**Comment by JeffreyBLewis** [comment]
I see the problem.  Very Web 1.0 over at the Census.  I guess that link 
was working for me because I had cookie or active session.  Maybe if you 
go back a page at

http://www.census.gov/rdo/data/113th_congressional_and_new_state_legislative_district_plans.html

you will find a link to what you are looking for?

Best,

Jeff

On 07/22/2013 11:14 AM, Alan deLevie wrote:

> For some reason nothing is showing up when I click the link. There's 
> just a
> page title, but no content related to downloading the 2013 files.
> 
> On Mon, Jul 22, 2013 at 2:10 PM, JeffreyBLewis 
> notifications@github.comwrote:
> 
> > Dear Alan,
> > 
> > That is is good question. I have not yet incorporated the new 113th
> > districts into my collection, you can download them at
> > http://www.census.gov/cgi-bin/geo/shapefilesrd13/layers.cgi. I hope to
> > do that in the next month or two.
> > 
> > Best,
> > 
> > Jeff
> > 
> > On 07/22/2013 10:56 AM, Alan deLevie wrote:
> > 
> > > May sound like a dumb question, but given that we're currently in the
> > > 113th Congress, are these files not suitable for describing current
> > > districts?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/JeffreyBLewis/congressional-district-boundaries/issues/1
> > 
> > > .
> > 
> > ## 
> > 
> > Jeffrey Lewis
> > Professor and Chair
> > Department of Political Science
> > UCLA
> > 
> > —
> > Reply to this email directly or view it on 
> > GitHubhttps://github.com/JeffreyBLewis/congressional-district-boundaries/issues/1#issuecomment-21363716
> > .
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/JeffreyBLewis/congressional-district-boundaries/issues/1#issuecomment-21363940.

## 

Jeffrey Lewis
Professor and Chair
Department of Political Science
UCLA

**Comment by adelevie** [comment]
I did find the link and was able to download a shp file...now all I have to do is convert it to geoJSON.

**Comment by benbalter** [comment]
@adelevie of course you've already opened an issue on this repository! For future reference, instructions for converting shapefiles to geojson can be found in this post, [How to convert shapefiles to geojson](http://ben.balter.com/2013/06/26/how-to-convert-shapefiles-to-geojson-for-use-on-github/)

**Comment by JeffreyBLewis** [comment]
Current shapes can be downloaded directly from the US Census.
